'use server';
/**
 * @fileOverview Generates a system design problem with a solution, reasoning, key concepts, diagrams, and problem type.
 *
 * - generateSystemDesignProblem - A function that generates a system design problem.
 * - GenerateSystemDesignProblemInput - The input type for the generateSystemDesignProblem function.
 * - GenerateSystemDesignProblemOutput - The return type for the generateSystemDesignProblem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSystemDesignProblemInputSchema = z.object({
  difficultyLevel: z
    .enum(['Easy', 'Medium', 'Hard'])
    .describe('The difficulty level of the system design problem.'),
  problemType: z
    .string()
    .optional()
    .describe('The type of system design problem to generate. If empty or not provided, a problem type will be generated by the AI.'),
});
export type GenerateSystemDesignProblemInput = z.infer<
  typeof GenerateSystemDesignProblemInputSchema
>;

const GenerateSystemDesignProblemOutputSchema = z.object({
  problemStatement: z.string().describe('The generated system design problem statement.'),
  solution: z.string().describe('The proposed solution to the system design problem, in detailed Markdown format. Include explanations for each component and their interactions.'),
  reasoning: z.string().describe('The reasoning behind the proposed solution, in detailed Markdown format. Explain the trade-offs and design choices made.'),
  keyConcepts: z.string().describe('The key concepts covered by the problem, as a comma-separated string.'),
  diagram: z.string().describe('A textual description of a diagram illustrating the system design solution.'),
  generatedProblemType: z.string().describe('The specific type of problem that was generated or used by the AI.'),
});
export type GenerateSystemDesignProblemOutput = z.infer<
  typeof GenerateSystemDesignProblemOutputSchema
>;

export async function generateSystemDesignProblem(
  input: GenerateSystemDesignProblemInput
): Promise<GenerateSystemDesignProblemOutput> {
  return generateSystemDesignProblemFlow(input);
}

const generateSystemDesignProblemPrompt = ai.definePrompt({
  name: 'generateSystemDesignProblemPrompt',
  input: {schema: GenerateSystemDesignProblemInputSchema},
  output: {schema: GenerateSystemDesignProblemOutputSchema},
  prompt: `You are an expert system design problem generator.
Your goal is to populate a JSON object with the following fields: "problemStatement", "solution", "reasoning", "keyConcepts", "diagram", and "generatedProblemType".

Inputs:
- Difficulty Level: {{{difficultyLevel}}}
{{#if problemType}}
- User-specified Problem Type: {{{problemType}}}
{{else}}
- User-specified Problem Type: (Not provided, please generate one)
{{/if}}

Instructions:

1.  **Determine the \`generatedProblemType\`**:
    {{#if problemType}}
    Use the user-specified problem type: "{{{problemType}}}".
    {{else}}
    Based on the "{{{difficultyLevel}}}" difficulty level, invent a specific and engaging system design problem type.
    Examples of problem types:
        - For Easy: "Design a basic URL shortener", "Design a simple hit counter for a webpage".
        - For Medium: "Design a real-time notification system for a social media app", "Design a scalable photo storage service".
        - For Hard: "Design a distributed logging system for a large-scale application", "Design a global video streaming service".
    Set the \`generatedProblemType\` field in your JSON output to this problem type (either user-specified or invented).
    {{/if}}

2.  **Generate Content for Other JSON Fields**:
    Using the determined \`generatedProblemType\` and the "{{{difficultyLevel}}}" difficulty level, generate content for the following fields:
    -   \`problemStatement\`: A clear and concise statement of the system to be designed.
    -   \`solution\`: A high-level proposed solution. **This must be in detailed Markdown format**, explaining each component, their interactions, and how they address the problem requirements. Include detailed explanations and considerations for scalability, reliability, and performance.
    -   \`reasoning\`: The rationale behind the key design choices in your solution. **This must be in detailed Markdown format**, explaining trade-offs considered (e.g., consistency vs. availability, latency vs. cost), why specific technologies or patterns were chosen over alternatives, and potential bottlenecks or limitations.
    -   \`keyConcepts\`: A comma-separated string of important system design concepts relevant to this problem and solution (e.g., Load Balancing, Caching, Database Sharding, CAP Theorem, Microservices, Message Queues, Data Replication).
    -   \`diagram\`: A textual description of a diagram that would visually represent your proposed system architecture. This description should be detailed enough for someone to sketch the diagram, including components, data flow, and interactions.

Ensure your output is a valid JSON object matching the schema.
`,
});

const generateSystemDesignProblemFlow = ai.defineFlow(
  {
    name: 'generateSystemDesignProblemFlow',
    inputSchema: GenerateSystemDesignProblemInputSchema,
    outputSchema: GenerateSystemDesignProblemOutputSchema,
  },
  async input => {
    const {output} = await generateSystemDesignProblemPrompt(input);
    return output!;
  }
);
