'use server';
/**
 * @fileOverview Generates a system design problem with a solution, reasoning, key concepts, diagram description, diagram image, and problem type.
 *
 * - generateSystemDesignProblem - A function that generates a system design problem.
 * - GenerateSystemDesignProblemInput - The input type for the generateSystemDesignProblem function.
 * - GenerateSystemDesignProblemOutput - The return type for the generateSystemDesignProblem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { generateDiagramImage } from './generate-diagram-image';

const GenerateSystemDesignProblemInputSchema = z.object({
  difficultyLevel: z
    .enum(['Easy', 'Medium', 'Hard'])
    .describe('The difficulty level of the system design problem.'),
  problemType: z
    .string()
    .optional()
    .describe('The type of system design problem to generate. If empty or not provided, a problem type will be generated by the AI.'),
});
export type GenerateSystemDesignProblemInput = z.infer<
  typeof GenerateSystemDesignProblemInputSchema
>;

const GenerateSystemDesignProblemOutputSchema = z.object({
  problemStatement: z.string().describe('The generated system design problem statement.'),
  solution: z.string().describe('The proposed solution to the system design problem, in detailed Markdown format. Include explanations for each component and their interactions.'),
  reasoning: z.string().describe('The reasoning behind the proposed solution, in detailed Markdown format. Explain the trade-offs and design choices made.'),
  keyConcepts: z.string().describe('The key concepts covered by the problem, as a comma-separated string.'),
  diagramDescription: z.string().describe('A detailed textual description for an AI image generation model to create a schematic diagram. This diagram should visually represent the proposed system architecture, highlighting key components, their connections, and data flow.'),
  diagramImageUri: z.string().optional().describe('A generated schematic diagram of the system design solution, as a data URI. This might be absent if image generation fails.'),
  generatedProblemType: z.string().describe('The specific type of problem that was generated or used by the AI.'),
});
export type GenerateSystemDesignProblemOutput = z.infer<
  typeof GenerateSystemDesignProblemOutputSchema
>;

export async function generateSystemDesignProblem(
  input: GenerateSystemDesignProblemInput
): Promise<GenerateSystemDesignProblemOutput> {
  return generateSystemDesignProblemFlow(input);
}

const generateSystemDesignProblemPrompt = ai.definePrompt({
  name: 'generateSystemDesignProblemPrompt',
  input: {schema: GenerateSystemDesignProblemInputSchema},
  output: {schema: GenerateSystemDesignProblemOutputSchema.omit({ diagramImageUri: true })}, // The prompt won't generate the image URI directly
  prompt: `You are an expert system design problem generator.
Your goal is to populate a JSON object with the following fields: "problemStatement", "solution", "reasoning", "keyConcepts", "diagramDescription", and "generatedProblemType".

Inputs:
- Difficulty Level: {{{difficultyLevel}}}
{{#if problemType}}
- User-specified Problem Type: {{{problemType}}}
{{else}}
- User-specified Problem Type: (Not provided, please generate one)
{{/if}}

Instructions:

1.  **Determine the \`generatedProblemType\`**:
    {{#if problemType}}
    Use the user-specified problem type: "{{{problemType}}}".
    {{else}}
    Based on the "{{{difficultyLevel}}}" difficulty level, invent a specific and engaging system design problem type.
    Examples of problem types:
        - For Easy: "Design a basic URL shortener", "Design a simple hit counter for a webpage".
        - For Medium: "Design a real-time notification system for a social media app", "Design a scalable photo storage service".
        - For Hard: "Design a distributed logging system for a large-scale application", "Design a global video streaming service".
    Set the \`generatedProblemType\` field in your JSON output to this problem type (either user-specified or invented).
    {{/if}}

2.  **Generate Content for Other JSON Fields**:
    Using the determined \`generatedProblemType\` and the "{{{difficultyLevel}}}" difficulty level, generate content for the following fields:
    -   \`problemStatement\`: A clear and concise statement of the system to be designed.
    -   \`solution\`: A high-level proposed solution. **This must be in detailed Markdown format**, explaining each component, their interactions, and how they address the problem requirements. Include detailed explanations and considerations for scalability, reliability, and performance.
    -   \`reasoning\`: The rationale behind the key design choices in your solution. **This must be in detailed Markdown format**, explaining trade-offs considered (e.g., consistency vs. availability, latency vs. cost), why specific technologies or patterns were chosen over alternatives, and potential bottlenecks or limitations.
    -   \`keyConcepts\`: A comma-separated string of important system design concepts relevant to this problem and solution (e.g., Load Balancing, Caching, Database Sharding, CAP Theorem, Microservices, Message Queues, Data Replication).
    -   \`diagramDescription\`: A detailed textual description for an AI image generation model to create a schematic diagram. This diagram should visually represent the proposed system architecture, highlighting key components, their connections, and data flow. Focus on clear, concise instructions for a visual schematic. For example: "A schematic diagram showing a user icon connecting via the internet (cloud icon) to a load balancer. The load balancer distributes requests to three rectangular application server blocks, labeled 'App Server'. Each app server has arrows pointing to a shared cylindrical database icon labeled 'Database' and a shared rectangular cache icon labeled 'Cache'. Data flow arrows should indicate request and response paths clearly."

Ensure your output is a valid JSON object matching the schema (excluding diagramImageUri).
`,
});

const generateSystemDesignProblemFlow = ai.defineFlow(
  {
    name: 'generateSystemDesignProblemFlow',
    inputSchema: GenerateSystemDesignProblemInputSchema,
    outputSchema: GenerateSystemDesignProblemOutputSchema,
  },
  async input => {
    const {output: mainContentOutput} = await generateSystemDesignProblemPrompt(input);

    if (!mainContentOutput) {
      throw new Error('Failed to generate main content for the system design problem.');
    }

    let diagramImageUri: string | undefined = undefined;
    if (mainContentOutput.diagramDescription) {
      try {
        // Generate diagram image in parallel (or sequentially if preferred)
        const imageOutput = await generateDiagramImage({ prompt: mainContentOutput.diagramDescription });
        diagramImageUri = imageOutput.imageDataUri;
      } catch (error) {
        console.error("Failed to generate diagram image:", error);
        // Proceed without the image URI if generation fails
      }
    }

    return {
      ...mainContentOutput,
      diagramImageUri: diagramImageUri,
    };
  }
);
