
# Dockerfile

# Stage 1: Build the Next.js application
FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependency files first for layer caching
COPY package.json package-lock.json ./

# npm install (not ci) to tolerate lock file generated by newer npm version
RUN npm install

# Copy source code
COPY . .

# Ensure public dir exists (project may not have one)
RUN mkdir -p /app/public

# Build the Next.js application (uses output: 'standalone' from next.config.ts)
RUN npm run build

# Stage 2: Serve the application
FROM gcr.io/distroless/nodejs22-debian12 AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# Copy standalone build (includes only necessary node_modules)
COPY --from=builder /app/.next/standalone ./
# Copy static assets (not included in standalone output)
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

USER nonroot

# Run the standalone server directly — no npm install needed
CMD ["node", "server.js"]
